### PR TITLE
Rename ans -> sol

### PR DESCRIPTION
**Pull request by matthieugomez**
ans returns the value of the last value in Julia, so I am not sure the tests were testing for anything.

Tests for NNPDENS fail for me after this correction

### CODE REVIEW

**Comment by matthieugomez** [comment]
How are you interpreting Travis vs AppVeyor?
Maybe each test could set a random seed?

**Comment by ChrisRackauckas** [comment]
Yeah I think it could just be some kind of tolerance thing. We should probably run the HJB one longer.

**Comment by ChrisRackauckas** [comment]
Should be fixed now, but it also doesn't change the results from what I could see: It doesn't seem to overwrite ans anymore if you explicitly write to it?

**Comment by ChrisRackauckas** [comment]
If it is an issue, this should get rebased to a newer version, it's just a bit too far back now!

**Pull request closed without merging**
